# Generated by Django 3.1.7 on 2021-04-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bolg_type',
            new_name='blog_type',
        ),
    ]
