# Generated by Django 3.1.7 on 2021-05-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210430_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
